Capstone
NatanimA/Miicroverse-Capstone-Module-One pull request #1
Opened 2022-09-14 13:10 UTC by NatanimA

Inserted mobile version for landing page and about page
Dynamic creation of featured speakers
Desktop version for both pages

2022-09-14 15:14 UTC, BertrandConxy requested changes
Hi @NatanimA, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 

## Highlights 💪 

- No linter errors
- correct flow is used
- good README

## Required Changes ♻️

- [ ] Among the capstone requirements, you are expected to present your project in a video and then add the link to the video in your Pull request. It will be better if you use the [Loom ](https://www.loom.com/looms) platform to record your video 😎 👍 

_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] I think it would be  better if name this project the same name as it is called, In other words, give it a specific name like `"Software Dev Bootcamp"` 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 15:14 UTC, BertrandConxy commented on README.md
> +>Design credit Cindy Shin in Behance
- [ ] Good job on using the README template provided 👏. However, **there are two sections that I would suggest you add. First is the `Getting started section`**  Please elaborate on more information in this section. This is where you describe the procedures to clone and run your project locally. **This is a helpful section for your fellow developers who may be interested in your project 😃**. So, please add it 🏃 the Second one is the `screenshot section` This is where you add a screenshot of the landing page of your website. This gives visitors a quick preview of what your website looks like therefore be more interested 😉 👍

2022-09-14 15:14 UTC, BertrandConxy commented on README.md
> +>Design credit Cindy Shin in Behance
- [ ] Please give credit and Acknowledgment to [Cindy Chin](https://www.behance.net/adagio07) the owner of the [original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) as required by the Creative Commons License 😃 👍 You can add it in the acknowledgement section 😉

2022-09-14 15:14 UTC, BertrandConxy commented on README.md
> +
- [ ] Please deploy your website using Github pages and then add the link in the Live Demo section in your README file 😉 👍

2022-09-14 15:14 UTC, BertrandConxy commented on about.html
> +                    <li class="nav-link"><a href="#partners">Our Partners</a></li>
- [ ] Please **add the link to the Home page so that users can browse through the Home page and the about page** very easily 😃 👍 
⚠️ Please make sure the navigation bar is **the same for both the Home page and the About page** 😃

2022-09-14 15:14 UTC, BertrandConxy commented on about.html
> +                    <li id="campaine" class="nav-link"><a href="#contacts">Cc Campaign</a></li>
- [ ] There is a top bar which is a part of the navigation bar as the project guidelines state. Please add it here in your desktop version 😃. Please take a look at the following screenshot 👇 

![image](https://user-images.githubusercontent.com/90222110/190187406-2786126d-9c5b-4473-8338-ae8ee939d203.png)

2022-09-14 15:14 UTC, BertrandConxy commented on about.html
> +            </nav>
- [ ] I think it would be better if you use only one HTML markup for the navigation links. Duplication of codes is considered a bad practice. The best practice is **not to repeat yourself**  😃 👍

2022-09-14 15:14 UTC, BertrandConxy commented on index.html
> +
- [ ] Please add the footer section in both your `index.html` and the `about.html`. You can check out its structure and design below 👇 

**Home footer**
![image](https://user-images.githubusercontent.com/90222110/190190155-58f53fe1-7de7-48ed-8217-a4f7b390e913.png)

**About footer**
![image](https://user-images.githubusercontent.com/90222110/190190871-d7068c18-4ef0-46be-8a30-776385784da3.png)

2022-09-14 15:14 UTC, BertrandConxy commented on index.html
> +                    </div>
- [ ] Please stick to the design given by using only four cards to make the alignment correct. Specifically, please remove this last card to remain with only one row 👍 
![image](https://user-images.githubusercontent.com/90222110/190193690-e7924f9d-95b4-4b36-844f-e2dc2e4bd850.png)

2022-09-15 13:05 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @NatanimA ✋

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" width="480" height="270" class="giphy-embed" />

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions

- [ ] Nice video presentation. However, it would have been better to use the loom features such as displaying your image in the video. You should have shared the entire screen so as to be easy to display the code snippet that was interesting for this project as was stated in the project requirements.

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-15 13:05 UTC, 1GORDON commented on css/style.css
> +}
Great job @NatanimA 🤝

- [ ] [Optional] Kindly make sure your about version doesn't include the partners' section in the footer.
- Your design
![about](https://user-images.githubusercontent.com/63917725/190410292-c624c563-e800-4dbe-aadc-70591218a476.PNG)

- Provided design
![design footer](https://user-images.githubusercontent.com/63917725/190410534-129216d0-5d2d-45c3-a36b-8bc67cb334b6.PNG)

2022-09-15 13:05 UTC, 1GORDON commented on index.html
> +                            <li>
Great job @NatanimA 🤝

- [ ] [Optional] As stated by the previous reviewer, Kindly make sure you don't repeat yourself. Your navigation code is duplicated both in the `index.html`, file and the `about.html` file. Code duplication is regarded as bad practice as it makes your project bulky and heavy.

2022-09-15 13:08 UTC, merged